name: modbus_tool
description: A Modbus Client implementation for OpenTool, allowing OpenTool call to operator Modbus.
version: 1.0.0
repository: https://github.com/opentool-hub/opentool-server-modbus

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  args: ^2.5.0
  json_annotation: ^4.9.0
  modbus_client: ^1.4.2
  modbus_client_tcp: ^1.2.3
  modbus_client_udp: ^1.4.0
  modbus_client_serial: ^1.3.1
  opentool_dart: ^1.1.0

dev_dependencies:
  build_runner: ^2.6.0
  json_serializable: ^6.10.0
